name: release

on:
  workflow_run:
    workflows: [ changelog ]
    types:
      - completed

jobs:
  release:
    name: "Publish release"
    runs-on: self-hosted

    steps:
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.previoustag.outputs.tag }}
          title: ${{ steps.previoustag.outputs.tag }}
          prerelease: false
          files: |
            CHANGELOG.md
            dist.zip
